name: Daily Commit

on:
  schedule:
    - cron: '0 4,16 * * *'  # Every day at 10 AM and 10 PM Bangladesh time (UTC+6)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update timestamp (Bangladesh time)
        run: |
          export TZ=Asia/Dhaka
          echo "Last update: $(date)" > last_update.txt

      - name: Commit changes
        run: |
          git add last_update.txt
          git commit -m "Daily update: $(date)" || echo "No changes to commit"

      - name: Push with GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:main
